# Site settings
title: Shanglong Zhang
email: shanglongzhang@gmail.com 
author: Shanglong Zhang
description: "Personal Website of Shanglong Zhang"
baseurl: ""
url: "网站url，如:http://pixyll.com"

# Build settings
markdown: kramdown
permalink: pretty
#每页文章数量
paginate: 3
